### ISSUE TITLE
MissingPluginException when using map_view

### ISSUE THREAD

**Issue by vladaman** [apptreesoftware/flutter_google_map_view#105]
Using map_view 0.0.14 I get following exception when trying to use static map:
```
08-14 10:44:40.184 6649-6671/cz.xxx.xxx I/flutter: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>'
08-14 10:44:40.201 6649-6671/cz.xxx.xxx E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    MissingPluginException(No implementation found for method show on channel com.apptreesoftware.map_view)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      MapView.show (package:map_view/map_view.dart:74:14)
    #2      _HistorieItemScreenState._buildMapView (package:xxxx/screens/historie_item.dart:503:14)
    #3      _HistorieItemScreenState._buildHistoryBox (package:xxxx/screens/historie_item.dart:131:19)
    #4      _HistorieItemScreenState._buildBody (package:xxxx/screens/historie_item.dart:99:7)
    #5      _HistorieItemScreenState.build.<anonymous closure> (package:xxxx/screens/historie_item.dart:72:51)
    #6      Builder.build (package:flutter/src/widgets/basic.dart:5377:41)
    #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
    #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
    #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
    #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
    #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
    #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
    #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
    #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
    #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
    #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
    #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
    #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
    #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
    #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)
```

**Comment by biscuitrainbow** [comment]
Did you try "flutter clean" ?
