### ISSUE TITLE
Not able to build on IOS (The 'Pods-Runner' target has transitive dependencies that include static binaries:)

### ISSUE THREAD

**Issue by rr0055256** [apptreesoftware/flutter_google_map_view#138]
Getting the below error while  running the app on IOS emulator

sing permission_handler (2.1.0)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/srinivasaks/Flutter
    Projects/sense_drive/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/srinivasaks/Flutter
    Projects/sense_drive/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /Users/srinivasaks/Flutter
    Projects/sense_drive/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)

    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:81:in
    `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in
    `each'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in
    `block in verify_no_static_framework_transitive_dependencies'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in
    `each'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in
    `verify_no_static_framework_transitive_dependencies'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:36:in
    `validate!'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /Users/srinivasaks/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
    /Users/srinivasaks/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
    /Users/srinivasaks/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

Error running pod install
Error launching application on iPhone XR

**Comment by michaelmass** [comment]
I have the same issue when creating my app using `flutter create -i swift`. So this is probably related to the `ios-language` flag.

**Comment by Kanunnikoff** [comment]
The same problem.
People write [here](https://github.com/flutter/flutter/issues/14161), that 

> seem to need s.static_framework = true in podspecs
