### ISSUE TITLE
cacoa po

### ISSUE THREAD

**Issue by chenrina168** [apptreesoftware/flutter_google_map_view#145]
Hi when i try add map view dep.. . it's alway show message like bellow when i try run it. How can we fixed it?

Launching lib/main.dart on iPhone 6 in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A map_view
      - Flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `map_view` from `.symlinks/plugins/map_view/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A GoogleMaps
      A map_view
      - Flutter

    Downloading dependencies

    -> Using Flutter (1.0.0)

    -> Installing GoogleMaps (2.7.0)
      > Copying GoogleMaps from `/Users/rinachen/Library/Caches/CocoaPods/Pods/Release/GoogleMaps/2.7.0-f79af` to `Pods/GoogleMaps`

    -> Installing map_view (0.0.12)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/rinachen/Desktop/Flutter/production/QMExpress/qm_express/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/rinachen/Desktop/Flutter/production/QMExpress/qm_express/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /Users/rinachen/Desktop/Flutter/production/QMExpress/qm_express/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:81:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone 6.

**Comment by Oscarworld** [comment]
I solved this problem by commenting use_frameworks! in ios/Runner/Podfile and installing cocoapods-1.5.3 (before was 1.6.0.beta.2).
