### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by qmoderninfluence** [apptreesoftware/flutter_google_map_view#84]
D8: Cannot fit requested classes in a single dex file. Try supplying a main-dex list.
# methods: 66181 > 65536
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/81, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/59.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/61.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/64.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/65.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/66.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/68.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/71.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/74.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/76.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/77.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/79.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/80.jar
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:326)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:397)
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor619.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/81, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/59.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/61.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/64.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/65.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/66.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/68.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/71.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/74.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/76.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/77.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/79.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/80.jar
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 56 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	... 59 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:67)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:62)
	... 62 more
	Suppressed: com.android.tools.r8.errors.DexOverflowException: Cannot fit requested classes in a single dex file (# methods: 66181 > 65536)
		at com.android.tools.r8.dex.VirtualFile.throwIfFull(VirtualFile.java:182)
		at com.android.tools.r8.dex.VirtualFile$MonoDexDistributor.run(VirtualFile.java:395)
		at com.android.tools.r8.dex.ApplicationWriter.distribute(ApplicationWriter.java:144)
		at com.android.tools.r8.dex.ApplicationWriter.write(ApplicationWriter.java:164)
		at com.android.tools.r8.D8.run(D8.java:167)
		at com.android.tools.r8.D8.lambda$run$0(D8.java:71)
		at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
		... 62 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/81, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/59.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/61.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/64.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/65.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/66.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/68.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/71.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/74.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/76.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/77.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/79.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/80.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle build failed: 1

**Comment by qmoderninfluence** [comment]
Launching lib/main.dart on MHA L29 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
D8: Cannot fit requested classes in a single dex file. Try supplying a main-dex list.
# methods: 65539 > 65536

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/3.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/52.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/53.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/56.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/88.jar, /Users/qing/Documents/GitHub/LoopLocal/loop_local/build/app/intermediates/transforms/dexBuilder/debug/89.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle build failed: 1

**Comment by matthewtsmith** [comment]
This is not something specific to this library. It sounds like you have to enable multidex on Android. You can find more info here: https://developer.android.com/studio/build/multidex
