### ISSUE TITLE
Error inflating class fragment

### ISSUE THREAD

**Issue by MarcinusX** [apptreesoftware/flutter_google_map_view#92]
I did everything from read.me tutorial, then I try to run this code:
```
MapView.setApiKey("mykey");
MapView mapView = new MapView();
mapView.show(
    new MapOptions(
        mapViewType: MapViewType.normal,
        showUserLocation: true,
        initialCameraPosition: new CameraPosition(
            new Location(45.5235258, -122.6732493), 14.0),
        title: "Recently Visited"),
    toolbarActions: [new ToolbarAction("Close", 1)]);

```
And I get following error. What am I doing wrong?
```
E/AndroidRuntime(14871): FATAL EXCEPTION: main
E/AndroidRuntime(14871): Process: co.uk.digitalappointments.swifter, PID: 14871
E/AndroidRuntime(14871): java.lang.RuntimeException: Unable to start activity ComponentInfo{co.uk.digitalappointments.swifter/com.apptreesoftware.mapview.MapActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
E/AndroidRuntime(14871): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2858)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(14871): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
E/AndroidRuntime(14871): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(14871): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
E/AndroidRuntime(14871): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14871): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(14871): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
E/AndroidRuntime(14871): Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
E/AndroidRuntime(14871): Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class fragment
E/AndroidRuntime(14871): Caused by: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/AndroidRuntime(14871): 	at com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):40)
E/AndroidRuntime(14871): 	at com.google.maps.api.android.lib6.auth.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):11)
E/AndroidRuntime(14871): 	at com.google.maps.api.android.lib6.impl.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):4)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.internal.b.a(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):24)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):69)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapFragmentDelegate(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):32)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):29)
E/AndroidRuntime(14871): 	at fc.onTransact(:com.google.android.gms.dynamite_mapsdynamite@12874023@12.8.74 (040400-204998136):12)
E/AndroidRuntime(14871): 	at android.os.Binder.transact(Binder.java:608)
E/AndroidRuntime(14871): 	at com.google.android.gms.internal.maps.zza.transactAndReadException(Unknown Source:7)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.internal.zzf.zzc(Unknown Source:8)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.SupportMapFragment$zzb.zzc(Unknown Source:31)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.SupportMapFragment$zzb.createDelegate(Unknown Source:2)
E/AndroidRuntime(14871): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zza(Unknown Source:42)
E/AndroidRuntime(14871): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onInflate(Unknown Source:5)
E/AndroidRuntime(14871): 	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source:45)
E/AndroidRuntime(14871): 	at android.support.v4.app.Fragment.onInflate(Fragment.java:1306)
E/AndroidRuntime(14871): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3672)
E/AndroidRuntime(14871): 	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
E/AndroidRuntime(14871): 	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:338)
E/AndroidRuntime(14871): 	at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
E/AndroidRuntime(14871): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
E/AndroidRuntime(14871): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
E/AndroidRuntime(14871): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/AndroidRuntime(14871): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(14871): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(14871): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/AndroidRuntime(14871): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
E/AndroidRuntime(14871): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
E/AndroidRuntime(14871): 	at com.apptreesoftware.mapview.MapActivity.onCreate(MapActivity.kt:31)
E/AndroidRuntime(14871): 	at android.app.Activity.performCreate(Activity.java:6982)
E/AndroidRuntime(14871): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2811)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(14871): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
E/AndroidRuntime(14871): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(14871): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(14871): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
E/AndroidRuntime(14871): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14871): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(14871): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

```

**Comment by MarcinusX** [comment]
Ok, my mistake, I have put `<meta-data>` tags under Activity instead of Application.
